include: "rules/common.smk"


rule all:
    input:
        workflow_outputs(),


include: "rules/refs.smk"
include: "rules/fastqc.smk"
include: "rules/trim.smk"
include: "rules/merge.smk"
include: "rules/align.smk"
include: "rules/featureCounts.smk"
include: "rules/salmon.smk"


localrules:
    genome_get,
    annotation_get,
