## Path to TSV file containing sample information (required columns: sample)
samples: ".test/config_se/samples.tsv"
## Path to TSV file containing sequencing unit information (required columns: sample, unit, fq1, fq2)
units: ".test/config_se/units.tsv"

ref:
  ## Ensembl species name
  species: danio_rerio
  ## Emsembl release
  release: 111
  ## Genome build
  build: GRCz11

## Read length of raw FASTQ data
## Used for calculating the maximum possible overhang for reads across splice junctions
## (i.e. for STAR's --sjdbOverhang paramter)
read_length: 98

## Boolean specifying whether FastQC output is desired
fastqc: True

## featureCounts configuration
featureCounts:
  ## Specify as True to produce gene-level counts
  activate: True
  ## Strandedness of the library, passed to the -s option
  ## 0: unstranded, 1: stranded, and 2: reversely stranded
  ## Requires a list. Multiple choices can be specified if the strandedness is unknown, producing a featureCounts output for each
  strandedness: [0, 1, 2]
  ## -J count the number of reads supporting each exon-exon junction
  ## -p indicates the BAM files contain paired-end data, omit this flag for single-end
  ## --countReadPairs count read pairs (fragments) instead of reads. Only required for paired end data. This was introduced in subread v2.0.2
  ## --fracOverlap minimum fraction of overlapping bases required for read assignment to a feature
  ## --minOverlap minimum number of overlapping bases required for read assignment to a feature
  extra: "-p --countReadPairs --fracOverlap 1 --minOverlap 35"

## salmon configuration
salmon:
  ## Specify as True to produce gene-level counts
  activate: True
  index:
    ## Extra params passed to salmon index
    extra: ""
  quant:
    ## Extra params passed to salmon quant
    extra: "--numBootstraps 100"