######
## COMMON CONFIG
######
## Edit the following configuration for a typical, minimal(-ish), RNA-seq
## analysis
## This involves QC, trimming, aligning, and quantification to the gene- and
## transcript-level

## Path to TSV file containing sample information (required columns: sample)
samples: ".test/config_se/samples.tsv"
## Path to TSV file containing sequencing unit information (required columns: sample, unit, fq1, fq2)
units: ".test/config_se/units.tsv"

## Path to raw data specified in units.tsv
data_dir: ".test/data"

ref:
  ## Ensembl species name
  species: danio_rerio
  ## Emsembl release
  release: 111
  ## Genome build
  build: GRCz11

## Read length of raw FASTQ data
## Used for calculating the maximum possible overhang for reads across splice junctions
## (i.e. for STAR's --sjdbOverhang paramter)
read_length: 98

## FastQC configuration
fastqc:
  ## Boolean specifying whether FastQC output is desired
  activate: True
  extra: "--noextract"

## fastp configuration
trim:
  ## Exclude `--detect_adapter_for_pe` for single-end
  extra: "--qualified_quality_phred 20 --length_required 35 --trim_poly_g"

## STAR configuration
align:
  ## Keep BAM files or automatically delete them
  keep_bam: True
  ## The align rule is configured to specify STAR's --sjdbOverhang parameter using the read_length defined above
  ## Specify any further parameters here
  extra: "--outSAMtype BAM SortedByCoordinate"

## featureCounts configuration
featureCounts:
  ## Specify as True to produce gene-level counts
  activate: True
  ## Strandedness of the library, passed to the -s option
  ## 0: unstranded, 1: stranded, and 2: reversely stranded
  ## Requires a list. Multiple choices can be specified if the strandedness is unknown, producing a featureCounts output for each
  strandedness: [0, 1, 2]
  ## -p indicates the BAM files contain paired-end data, omit this flag for single-end
  ## --countReadPairs count read pairs (fragments) instead of reads. Only required for paired end data. This was introduced in subread v2.0.2
  ## Exclude `-p --countReadPairs` for single-end
  extra: ""

## Salmon configuration
salmon:
  ## Specify as True to produce transcript-level counts
  activate: True
  index:
    ## Extra params passed to salmon index
    extra: ""
  quant:
    ## Library type
    ## "A" allows Salmon to automatically infer the library type
    libtype: "A"
    ## Extra params passed to salmon quant
    extra: ""

######
## OPTIONAL CONFIG
######
## The configuration options here are deactivated by default
## Activate these if you require additional QC, deeper analysis, or niche
## processing of your data

## UMI-tools configuration
deduplicate:
  ## Boolean to specify whether alignments should be deduplicated by UMI and position
  activate: True
  ## Extra params passed to UMI-tools
  ## Exclude `--paired` for single-end
  extra: "--umi-separator=:"

## RSeQC configuration
read_distribution:
  activate: True
inner_distance:
  activate: True

## rRNA detection
rrna:
  activate: True

## Genome coverage
coverage:
  activate: True
  keep_bedGraphs: True
